// Code generated by go-swagger; DO NOT EDIT.

package spaces

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/Slava02/Involvio/internal/entity"
)

// CreateSpaceOKCode is the HTTP code returned for type CreateSpaceOK
const CreateSpaceOKCode int = 200

/*
CreateSpaceOK Successful operation

swagger:response createSpaceOK
*/
type CreateSpaceOK struct {

	/*
	  In: Body
	*/
	Payload *entity.Space `json:"body,omitempty"`
}

// NewCreateSpaceOK creates CreateSpaceOK with default headers values
func NewCreateSpaceOK() *CreateSpaceOK {

	return &CreateSpaceOK{}
}

// WithPayload adds the payload to the create space o k response
func (o *CreateSpaceOK) WithPayload(payload *entity.Space) *CreateSpaceOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create space o k response
func (o *CreateSpaceOK) SetPayload(payload *entity.Space) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateSpaceOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateSpaceBadRequestCode is the HTTP code returned for type CreateSpaceBadRequest
const CreateSpaceBadRequestCode int = 400

/*
CreateSpaceBadRequest Invalid data supplied

swagger:response createSpaceBadRequest
*/
type CreateSpaceBadRequest struct {
}

// NewCreateSpaceBadRequest creates CreateSpaceBadRequest with default headers values
func NewCreateSpaceBadRequest() *CreateSpaceBadRequest {

	return &CreateSpaceBadRequest{}
}

// WriteResponse to the client
func (o *CreateSpaceBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// CreateSpaceInternalServerErrorCode is the HTTP code returned for type CreateSpaceInternalServerError
const CreateSpaceInternalServerErrorCode int = 500

/*
CreateSpaceInternalServerError Internal service error

swagger:response createSpaceInternalServerError
*/
type CreateSpaceInternalServerError struct {
}

// NewCreateSpaceInternalServerError creates CreateSpaceInternalServerError with default headers values
func NewCreateSpaceInternalServerError() *CreateSpaceInternalServerError {

	return &CreateSpaceInternalServerError{}
}

// WriteResponse to the client
func (o *CreateSpaceInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
