// Code generated by go-swagger; DO NOT EDIT.

package entity

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DeleteUserReq delete user req
//
// swagger:model DeleteUserReq
type DeleteUserReq struct {

	// space id
	// Example: 1234
	SpaceID int64 `json:"space_id,omitempty"`
}

// Validate validates this delete user req
func (m *DeleteUserReq) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this delete user req based on context it is used
func (m *DeleteUserReq) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DeleteUserReq) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DeleteUserReq) UnmarshalBinary(b []byte) error {
	var res DeleteUserReq
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
