// Code generated by go-swagger; DO NOT EDIT.

package entity

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// TagOptions tag options
//
// swagger:model TagOptions
type TagOptions []map[string][]string

// Validate validates this tag options
func (m TagOptions) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this tag options based on context it is used
func (m TagOptions) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
