// Code generated by go-swagger; DO NOT EDIT.

// Package route Involvio
//
//	Endpoints for pet-project involvio
//	Schemes:
//	  http
//	Host: localhost
//	BasePath: /
//	Version: 1.0.0
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package route
