// Code generated by go-swagger; DO NOT EDIT.

package route

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "swagger": "2.0",
  "info": {
    "description": "Endpoints for pet-project involvio",
    "title": "Involvio",
    "version": "1.0.0"
  },
  "paths": {
    "/events": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "events"
        ],
        "summary": "Create event",
        "operationId": "createEvent",
        "parameters": [
          {
            "description": "info about event",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/CreateEventReq"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "schema": {
              "$ref": "#/definitions/Event"
            }
          },
          "400": {
            "description": "Invalid data supplied"
          },
          "404": {
            "description": "Event not found"
          },
          "500": {
            "description": "Internal service error"
          }
        }
      }
    },
    "/events/{eventId}": {
      "get": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "events"
        ],
        "summary": "event info",
        "operationId": "getEvent",
        "parameters": [
          {
            "type": "integer",
            "description": "event to get info about",
            "name": "eventId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#/definitions/EventInfoResp"
            }
          },
          "400": {
            "description": "Invalid data supplied"
          },
          "404": {
            "description": "Event not found"
          },
          "500": {
            "description": "Internal service error"
          }
        }
      }
    },
    "/events/{eventId}/join": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "events"
        ],
        "summary": "join event",
        "operationId": "joinEvent",
        "parameters": [
          {
            "type": "integer",
            "description": "eventId to join",
            "name": "eventId",
            "in": "path",
            "required": true
          },
          {
            "description": "userId",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/JoinEventReq"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation"
          },
          "400": {
            "description": "Invalid data supplied"
          },
          "404": {
            "description": "Event not found"
          },
          "500": {
            "description": "Internal service error"
          }
        }
      }
    },
    "/spaces": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "spaces"
        ],
        "summary": "create a space",
        "operationId": "createSpace",
        "parameters": [
          {
            "description": "adminId and tags for space",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/CreateSpaceReq"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "schema": {
              "$ref": "#/definitions/Space"
            }
          },
          "400": {
            "description": "Invalid data supplied"
          },
          "500": {
            "description": "Internal service error"
          }
        }
      }
    },
    "/spaces/{spaceId}": {
      "get": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "spaces"
        ],
        "summary": "get space info",
        "operationId": "getSpace",
        "parameters": [
          {
            "type": "integer",
            "description": "space id that is needed",
            "name": "spaceId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "schema": {
              "$ref": "#/definitions/Space"
            }
          },
          "400": {
            "description": "Invalid data supplied"
          },
          "404": {
            "description": "Space not found"
          },
          "500": {
            "description": "Internal service error"
          }
        }
      }
    },
    "/spaces/{spaceId}/join": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "spaces"
        ],
        "summary": "join space",
        "operationId": "joinSpace",
        "parameters": [
          {
            "type": "integer",
            "description": "space id to join",
            "name": "spaceId",
            "in": "path",
            "required": true
          },
          {
            "description": "user info",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/User"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation"
          },
          "400": {
            "description": "Invalid data supplied"
          },
          "404": {
            "description": "Space not found"
          },
          "500": {
            "description": "Internal service error"
          }
        }
      }
    },
    "/users": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "user"
        ],
        "summary": "create user",
        "operationId": "createUser",
        "parameters": [
          {
            "description": "user info",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/User"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#/definitions/User"
            }
          },
          "400": {
            "description": "Invalid data supplied"
          },
          "500": {
            "description": "Internal service error"
          }
        }
      }
    },
    "/users/{userId}": {
      "get": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "user"
        ],
        "summary": "show profile",
        "operationId": "get user",
        "parameters": [
          {
            "type": "integer",
            "name": "userId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#/definitions/UserInfoResp"
            }
          },
          "400": {
            "description": "Invalid data supplied"
          },
          "404": {
            "description": "User not found"
          },
          "500": {
            "description": "Internal service error"
          }
        }
      },
      "delete": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "user"
        ],
        "summary": "delete user",
        "operationId": "deleteUser",
        "parameters": [
          {
            "type": "integer",
            "description": "userId to delete",
            "name": "userId",
            "in": "path",
            "required": true
          },
          {
            "description": "updated userInfo",
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/DeleteUserReq"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation"
          },
          "400": {
            "description": "Invalid data supplied"
          },
          "404": {
            "description": "User not found"
          },
          "500": {
            "description": "Internal service error"
          }
        }
      },
      "patch": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "user"
        ],
        "summary": "update user form/info, promote/reduce user privilege",
        "operationId": "updateUser",
        "parameters": [
          {
            "type": "integer",
            "description": "userId to make action with",
            "name": "userId",
            "in": "path",
            "required": true
          },
          {
            "description": "updated userInfo",
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/Form"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation"
          },
          "400": {
            "description": "Invalid data supplied"
          },
          "404": {
            "description": "User not found"
          },
          "500": {
            "description": "Internal service error"
          }
        }
      }
    }
  },
  "definitions": {
    "CreateEventReq": {
      "type": "object",
      "properties": {
        "event": {
          "$ref": "#/definitions/Event"
        },
        "space_id": {
          "type": "integer",
          "example": 1234
        },
        "user_id": {
          "type": "integer",
          "example": 1234
        }
      }
    },
    "CreateSpaceReq": {
      "type": "object",
      "properties": {
        "admin_id": {
          "type": "integer",
          "example": 1234
        },
        "space_description": {
          "type": "string",
          "example": "space for test"
        },
        "space_id": {
          "type": "integer",
          "example": 1234
        },
        "space_name": {
          "type": "string",
          "example": "test"
        },
        "tags": {
          "$ref": "#/definitions/TagOptions"
        }
      }
    },
    "DeleteUserReq": {
      "type": "object",
      "properties": {
        "space_id": {
          "type": "integer",
          "example": 1234
        }
      }
    },
    "Event": {
      "type": "object",
      "properties": {
        "begin_date": {
          "type": "string",
          "format": "date-time",
          "example": "11.01.2002 12:00"
        },
        "description": {
          "type": "string",
          "example": "enormously fun event"
        },
        "end_date": {
          "type": "string",
          "format": "date-time",
          "example": "11.01.2002 12:00"
        },
        "name": {
          "type": "string",
          "example": "fun event"
        },
        "tags": {
          "$ref": "#/definitions/Tags"
        }
      }
    },
    "EventInfoResp": {
      "type": "object",
      "properties": {
        "event": {
          "$ref": "#/definitions/Event"
        },
        "users": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/User"
          }
        }
      }
    },
    "Form": {
      "type": "object",
      "properties": {
        "admin": {
          "type": "boolean",
          "example": true
        },
        "creator": {
          "type": "boolean",
          "example": true
        },
        "pair_tags": {
          "$ref": "#/definitions/Tags"
        },
        "spaceId": {
          "type": "integer",
          "example": 123
        },
        "user_tags": {
          "$ref": "#/definitions/Tags"
        }
      }
    },
    "JoinEventReq": {
      "type": "object",
      "properties": {
        "user_id": {
          "type": "integer",
          "example": 1234
        }
      }
    },
    "Space": {
      "type": "object",
      "properties": {
        "space_description": {
          "type": "string",
          "example": "space for test"
        },
        "space_id": {
          "type": "integer",
          "example": 1234
        },
        "space_name": {
          "type": "string",
          "example": "test"
        },
        "tags": {
          "$ref": "#/definitions/TagOptions"
        }
      }
    },
    "TagOptions": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "example": [
            "1",
            "2",
            "3"
          ]
        },
        "example": {
          "course": [
            "math",
            "cs",
            "philosophy"
          ]
        }
      }
    },
    "Tags": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": {
          "type": "string"
        },
        "example": {
          "course": "math"
        }
      }
    },
    "User": {
      "type": "object",
      "properties": {
        "auth_date": {
          "type": "string",
          "format": "date-time",
          "example": "11.01.2002 12:00"
        },
        "first_name": {
          "type": "string",
          "example": "ivan"
        },
        "last_name": {
          "type": "string",
          "example": "pupkin"
        },
        "photo_url": {
          "type": "string",
          "example": "http://my_photo"
        },
        "user_id": {
          "type": "integer",
          "example": 1234
        },
        "username": {
          "type": "string",
          "example": "ivan_pupk123"
        }
      }
    },
    "UserInfoResp": {
      "type": "object",
      "properties": {
        "forms": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Form"
          }
        },
        "user": {
          "$ref": "#/definitions/User"
        }
      }
    }
  },
  "tags": [
    {
      "name": "spaces"
    },
    {
      "name": "events"
    },
    {
      "name": "users"
    }
  ]
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "swagger": "2.0",
  "info": {
    "description": "Endpoints for pet-project involvio",
    "title": "Involvio",
    "version": "1.0.0"
  },
  "paths": {
    "/events": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "events"
        ],
        "summary": "Create event",
        "operationId": "createEvent",
        "parameters": [
          {
            "description": "info about event",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/CreateEventReq"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "schema": {
              "$ref": "#/definitions/Event"
            }
          },
          "400": {
            "description": "Invalid data supplied"
          },
          "404": {
            "description": "Event not found"
          },
          "500": {
            "description": "Internal service error"
          }
        }
      }
    },
    "/events/{eventId}": {
      "get": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "events"
        ],
        "summary": "event info",
        "operationId": "getEvent",
        "parameters": [
          {
            "type": "integer",
            "description": "event to get info about",
            "name": "eventId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#/definitions/EventInfoResp"
            }
          },
          "400": {
            "description": "Invalid data supplied"
          },
          "404": {
            "description": "Event not found"
          },
          "500": {
            "description": "Internal service error"
          }
        }
      }
    },
    "/events/{eventId}/join": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "events"
        ],
        "summary": "join event",
        "operationId": "joinEvent",
        "parameters": [
          {
            "type": "integer",
            "description": "eventId to join",
            "name": "eventId",
            "in": "path",
            "required": true
          },
          {
            "description": "userId",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/JoinEventReq"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation"
          },
          "400": {
            "description": "Invalid data supplied"
          },
          "404": {
            "description": "Event not found"
          },
          "500": {
            "description": "Internal service error"
          }
        }
      }
    },
    "/spaces": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "spaces"
        ],
        "summary": "create a space",
        "operationId": "createSpace",
        "parameters": [
          {
            "description": "adminId and tags for space",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/CreateSpaceReq"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "schema": {
              "$ref": "#/definitions/Space"
            }
          },
          "400": {
            "description": "Invalid data supplied"
          },
          "500": {
            "description": "Internal service error"
          }
        }
      }
    },
    "/spaces/{spaceId}": {
      "get": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "spaces"
        ],
        "summary": "get space info",
        "operationId": "getSpace",
        "parameters": [
          {
            "type": "integer",
            "description": "space id that is needed",
            "name": "spaceId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "schema": {
              "$ref": "#/definitions/Space"
            }
          },
          "400": {
            "description": "Invalid data supplied"
          },
          "404": {
            "description": "Space not found"
          },
          "500": {
            "description": "Internal service error"
          }
        }
      }
    },
    "/spaces/{spaceId}/join": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "spaces"
        ],
        "summary": "join space",
        "operationId": "joinSpace",
        "parameters": [
          {
            "type": "integer",
            "description": "space id to join",
            "name": "spaceId",
            "in": "path",
            "required": true
          },
          {
            "description": "user info",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/User"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation"
          },
          "400": {
            "description": "Invalid data supplied"
          },
          "404": {
            "description": "Space not found"
          },
          "500": {
            "description": "Internal service error"
          }
        }
      }
    },
    "/users": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "user"
        ],
        "summary": "create user",
        "operationId": "createUser",
        "parameters": [
          {
            "description": "user info",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/User"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#/definitions/User"
            }
          },
          "400": {
            "description": "Invalid data supplied"
          },
          "500": {
            "description": "Internal service error"
          }
        }
      }
    },
    "/users/{userId}": {
      "get": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "user"
        ],
        "summary": "show profile",
        "operationId": "get user",
        "parameters": [
          {
            "type": "integer",
            "name": "userId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#/definitions/UserInfoResp"
            }
          },
          "400": {
            "description": "Invalid data supplied"
          },
          "404": {
            "description": "User not found"
          },
          "500": {
            "description": "Internal service error"
          }
        }
      },
      "delete": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "user"
        ],
        "summary": "delete user",
        "operationId": "deleteUser",
        "parameters": [
          {
            "type": "integer",
            "description": "userId to delete",
            "name": "userId",
            "in": "path",
            "required": true
          },
          {
            "description": "updated userInfo",
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/DeleteUserReq"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation"
          },
          "400": {
            "description": "Invalid data supplied"
          },
          "404": {
            "description": "User not found"
          },
          "500": {
            "description": "Internal service error"
          }
        }
      },
      "patch": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "user"
        ],
        "summary": "update user form/info, promote/reduce user privilege",
        "operationId": "updateUser",
        "parameters": [
          {
            "type": "integer",
            "description": "userId to make action with",
            "name": "userId",
            "in": "path",
            "required": true
          },
          {
            "description": "updated userInfo",
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/Form"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation"
          },
          "400": {
            "description": "Invalid data supplied"
          },
          "404": {
            "description": "User not found"
          },
          "500": {
            "description": "Internal service error"
          }
        }
      }
    }
  },
  "definitions": {
    "CreateEventReq": {
      "type": "object",
      "properties": {
        "event": {
          "$ref": "#/definitions/Event"
        },
        "space_id": {
          "type": "integer",
          "example": 1234
        },
        "user_id": {
          "type": "integer",
          "example": 1234
        }
      }
    },
    "CreateSpaceReq": {
      "type": "object",
      "properties": {
        "admin_id": {
          "type": "integer",
          "example": 1234
        },
        "space_description": {
          "type": "string",
          "example": "space for test"
        },
        "space_id": {
          "type": "integer",
          "example": 1234
        },
        "space_name": {
          "type": "string",
          "example": "test"
        },
        "tags": {
          "$ref": "#/definitions/TagOptions"
        }
      }
    },
    "DeleteUserReq": {
      "type": "object",
      "properties": {
        "space_id": {
          "type": "integer",
          "example": 1234
        }
      }
    },
    "Event": {
      "type": "object",
      "properties": {
        "begin_date": {
          "type": "string",
          "format": "date-time",
          "example": "11.01.2002 12:00"
        },
        "description": {
          "type": "string",
          "example": "enormously fun event"
        },
        "end_date": {
          "type": "string",
          "format": "date-time",
          "example": "11.01.2002 12:00"
        },
        "name": {
          "type": "string",
          "example": "fun event"
        },
        "tags": {
          "$ref": "#/definitions/Tags"
        }
      }
    },
    "EventInfoResp": {
      "type": "object",
      "properties": {
        "event": {
          "$ref": "#/definitions/Event"
        },
        "users": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/User"
          }
        }
      }
    },
    "Form": {
      "type": "object",
      "properties": {
        "admin": {
          "type": "boolean",
          "example": true
        },
        "creator": {
          "type": "boolean",
          "example": true
        },
        "pair_tags": {
          "$ref": "#/definitions/Tags"
        },
        "spaceId": {
          "type": "integer",
          "example": 123
        },
        "user_tags": {
          "$ref": "#/definitions/Tags"
        }
      }
    },
    "JoinEventReq": {
      "type": "object",
      "properties": {
        "user_id": {
          "type": "integer",
          "example": 1234
        }
      }
    },
    "Space": {
      "type": "object",
      "properties": {
        "space_description": {
          "type": "string",
          "example": "space for test"
        },
        "space_id": {
          "type": "integer",
          "example": 1234
        },
        "space_name": {
          "type": "string",
          "example": "test"
        },
        "tags": {
          "$ref": "#/definitions/TagOptions"
        }
      }
    },
    "TagOptions": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "example": [
            "1",
            "2",
            "3"
          ]
        },
        "example": {
          "course": [
            "math",
            "cs",
            "philosophy"
          ]
        }
      }
    },
    "Tags": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": {
          "type": "string"
        },
        "example": {
          "course": "math"
        }
      }
    },
    "User": {
      "type": "object",
      "properties": {
        "auth_date": {
          "type": "string",
          "format": "date-time",
          "example": "11.01.2002 12:00"
        },
        "first_name": {
          "type": "string",
          "example": "ivan"
        },
        "last_name": {
          "type": "string",
          "example": "pupkin"
        },
        "photo_url": {
          "type": "string",
          "example": "http://my_photo"
        },
        "user_id": {
          "type": "integer",
          "example": 1234
        },
        "username": {
          "type": "string",
          "example": "ivan_pupk123"
        }
      }
    },
    "UserInfoResp": {
      "type": "object",
      "properties": {
        "forms": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Form"
          }
        },
        "user": {
          "$ref": "#/definitions/User"
        }
      }
    }
  },
  "tags": [
    {
      "name": "spaces"
    },
    {
      "name": "events"
    },
    {
      "name": "users"
    }
  ]
}`))
}
