BEGIN;

DROP TABLE IF EXISTS category_event;
DROP TABLE IF EXISTS user_event;
DROP TABLE IF EXISTS user_space;
DROP TABLE IF EXISTS "user";
DROP TABLE IF EXISTS category_space;
DROP TABLE IF EXISTS event;
DROP TABLE IF EXISTS category;
DROP TABLE IF EXISTS space;

COMMIT;