// Code generated by go-swagger; DO NOT EDIT.

package events

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/Slava02/Involvio/internal/entity"
)

// CreateEventOKCode is the HTTP code returned for type CreateEventOK
const CreateEventOKCode int = 200

/*
CreateEventOK Successful operation

swagger:response createEventOK
*/
type CreateEventOK struct {

	/*
	  In: Body
	*/
	Payload *entity.Event `json:"body,omitempty"`
}

// NewCreateEventOK creates CreateEventOK with default headers values
func NewCreateEventOK() *CreateEventOK {

	return &CreateEventOK{}
}

// WithPayload adds the payload to the create event o k response
func (o *CreateEventOK) WithPayload(payload *entity.Event) *CreateEventOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create event o k response
func (o *CreateEventOK) SetPayload(payload *entity.Event) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateEventOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateEventBadRequestCode is the HTTP code returned for type CreateEventBadRequest
const CreateEventBadRequestCode int = 400

/*
CreateEventBadRequest Invalid data supplied

swagger:response createEventBadRequest
*/
type CreateEventBadRequest struct {
}

// NewCreateEventBadRequest creates CreateEventBadRequest with default headers values
func NewCreateEventBadRequest() *CreateEventBadRequest {

	return &CreateEventBadRequest{}
}

// WriteResponse to the client
func (o *CreateEventBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// CreateEventNotFoundCode is the HTTP code returned for type CreateEventNotFound
const CreateEventNotFoundCode int = 404

/*
CreateEventNotFound Event not found

swagger:response createEventNotFound
*/
type CreateEventNotFound struct {
}

// NewCreateEventNotFound creates CreateEventNotFound with default headers values
func NewCreateEventNotFound() *CreateEventNotFound {

	return &CreateEventNotFound{}
}

// WriteResponse to the client
func (o *CreateEventNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// CreateEventInternalServerErrorCode is the HTTP code returned for type CreateEventInternalServerError
const CreateEventInternalServerErrorCode int = 500

/*
CreateEventInternalServerError Internal service error

swagger:response createEventInternalServerError
*/
type CreateEventInternalServerError struct {
}

// NewCreateEventInternalServerError creates CreateEventInternalServerError with default headers values
func NewCreateEventInternalServerError() *CreateEventInternalServerError {

	return &CreateEventInternalServerError{}
}

// WriteResponse to the client
func (o *CreateEventInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
