// Code generated by go-swagger; DO NOT EDIT.

package events

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetEventHandlerFunc turns a function with the right signature into a get event handler
type GetEventHandlerFunc func(GetEventParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetEventHandlerFunc) Handle(params GetEventParams) middleware.Responder {
	return fn(params)
}

// GetEventHandler interface for that can handle valid get event params
type GetEventHandler interface {
	Handle(GetEventParams) middleware.Responder
}

// NewGetEvent creates a new http.Handler for the get event operation
func NewGetEvent(ctx *middleware.Context, handler GetEventHandler) *GetEvent {
	return &GetEvent{Context: ctx, Handler: handler}
}

/*
	GetEvent swagger:route GET /events/{eventId} events getEvent

event info
*/
type GetEvent struct {
	Context *middleware.Context
	Handler GetEventHandler
}

func (o *GetEvent) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetEventParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
