// Code generated by go-swagger; DO NOT EDIT.

package events

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// JoinEventHandlerFunc turns a function with the right signature into a join event handler
type JoinEventHandlerFunc func(JoinEventParams) middleware.Responder

// Handle executing the request and returning a response
func (fn JoinEventHandlerFunc) Handle(params JoinEventParams) middleware.Responder {
	return fn(params)
}

// JoinEventHandler interface for that can handle valid join event params
type JoinEventHandler interface {
	Handle(JoinEventParams) middleware.Responder
}

// NewJoinEvent creates a new http.Handler for the join event operation
func NewJoinEvent(ctx *middleware.Context, handler JoinEventHandler) *JoinEvent {
	return &JoinEvent{Context: ctx, Handler: handler}
}

/*
	JoinEvent swagger:route POST /events/{eventId}/join events joinEvent

join event
*/
type JoinEvent struct {
	Context *middleware.Context
	Handler JoinEventHandler
}

func (o *JoinEvent) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewJoinEventParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
