swagger: "2.0"

######################################################################
#                             API INFO                               #
######################################################################

info:
  description: Endpoints for pet-project involvio
  version: 1.0.0
  title: Involvio
tags:
  - name: spaces
  - name: events
  - name: users

######################################################################
#                             PATHS                                  #
######################################################################
paths:
  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  /spaces:
    post:
      tags:
        - spaces
      summary: create a space
      operationId: createSpace
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          description: adminId and tags for space
          required: true
          schema:
            $ref: '#/definitions/CreateSpaceReq'
      responses:
        200:
          description: Successful operation
          schema:
            $ref:  '#/definitions/Space'
        400:
          description: Invalid data supplied
        500:
          description: Internal service error
  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  /spaces/{spaceId}:
    get:
      tags:
        - spaces
      summary: get space info
      operationId: getSpace
      produces:
        - application/json
      parameters:
        - name: spaceId
          in: path
          description: space id that is needed
          required: true
          type: integer
      responses:
        200:
          description: Successful operation
          schema:
            $ref: '#/definitions/Space'
        400:
          description: Invalid data supplied
        404:
          description: Space not found
        500:
          description: Internal service error
  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  /spaces/{spaceId}/join:
    post:
      tags:
        - spaces
      summary: join space
      operationId: joinSpace
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: spaceId
          in: path
          description: space id to join
          required: true
          type: integer
        - name: body
          in: body
          description: user info
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        200:
          description: Successful operation
        400:
          description: Invalid data supplied
        404:
          description: Space not found
        500:
          description: Internal service error
######################################################################
  /events:
    post:
      tags:
        - events
      summary: Create event
      operationId: createEvent
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          description: info about event
          schema:
            $ref: '#/definitions/CreateEventReq'
          required: true
      responses:
        200:
          description: Successful operation
          schema:
            $ref: '#/definitions/Event'
        400:
          description: Invalid data supplied
        404:
          description: Event not found
        500:
          description: Internal service error
  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  /events/{eventId}:
    get:
      tags:
        - events
      summary: event info
      operationId: getEvent
      produces:
        - application/json
      parameters:
        - name: eventId
          in: path
          description: event to get info about
          required: true
          type: integer
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/EventInfoResp'
        400:
          description: Invalid data supplied
        404:
          description: Event not found
        500:
          description: Internal service error
  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  /events/{eventId}/join:
    post:
      tags:
        - events
      summary: join event
      operationId: joinEvent
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: eventId
          in: path
          description: eventId to join
          required: true
          type: integer
        - name: body
          in: body
          description: userId
          required: true
          schema:
            $ref: '#/definitions/JoinEventReq'
      responses:
        200:
          description: successful operation
        400:
          description: Invalid data supplied
        404:
          description: Event not found
        500:
          description: Internal service error
######################################################################
  /users:
    post:
      tags:
        - user
      summary: create user
      operationId: createUser
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          description: user info
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/User'
        400:
          description: Invalid data supplied
        500:
          description: Internal service error
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  /users/{userId}:
    get:
      tags:
        - user
      summary: show profile
      operationId: get user
      produces:
        - application/json
      parameters:
        - name: userId
          in: path
          required: true
          type: integer
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/UserInfoResp'
        400:
          description: Invalid data supplied
        404:
          description: User not found
        500:
          description: Internal service error
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
    patch:
      tags:
        - user
      summary: update user form/info, promote/reduce user privilege
      operationId: updateUser
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: userId
          in: path
          description: userId to make action with
          required: true
          type: integer
        - name: body
          in: body
          description: updated userInfo
          schema:
            $ref: '#/definitions/Form'
      responses:
        200:
          description: successful operation
        400:
          description: Invalid data supplied
        404:
          description: User not found
        500:
          description: Internal service error
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
    delete:
      tags:
        - user
      summary: delete user
      operationId: deleteUser
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: userId
          in: path
          description: userId to delete
          required: true
          type: integer
        - name: body
          in: body
          description: updated userInfo
          schema:
            $ref: '#/definitions/DeleteUserReq'
      responses:
        200:
          description: successful operation
        400:
          description: Invalid data supplied
        404:
          description: User not found
        500:
          description: Internal service error
######################################################################
#                             DEFINITIONS                            #
######################################################################
definitions:
######################################################################
#                             REQUESTS                              #
######################################################################
  CreateSpaceReq:
    type: object
    properties:
      admin_id:
        type: integer
        example: 1234
      space_id:
        type: integer
        example: 1234
      space_name:
        type: string
        example: test
      space_description:
        type: string
        example: space for test
      tags:
        $ref: '#/definitions/TagOptions'
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  CreateEventReq:
    type: object
    properties:
      user_id:
        type: integer
        example: 1234
      space_id:
        type: integer
        example: 1234
      event:
        $ref: '#/definitions/Event'
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  JoinEventReq:
    type: object
    properties:
      user_id:
        type: integer
        example: 1234
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  DeleteUserReq:
    type: object
    properties:
      space_id:
        type: integer
        example: 1234
######################################################################
#                             RESPONSES                              #
######################################################################
  EventInfoResp:
    type: object
    properties:
      event:
        $ref: '#/definitions/Event'
      users:
        type: array
        items:
          $ref: '#/definitions/User'
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  UserInfoResp:
    type: object
    properties:
      user:
        $ref: '#/definitions/User'
      forms:
        type: array
        items:
          $ref: '#/definitions/Form'
######################################################################
#                             ENTITIES                               #
######################################################################
  User:
    type: object
    properties:
      user_id:
        type: integer
        example: 1234
      first_name:
        type: string
        example: ivan
      last_name:
        type: string
        example: pupkin
      username:
        type: string
        example: ivan_pupk123
      photo_url:
        type: string
        example: http://my_photo
      auth_date:
        type: string
        format: date-time
        example: 11.01.2002 12:00
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  Form:
    type: object
    properties:
      spaceId:
        type: integer
        example: 123
      admin:
        type: boolean
        example: true
      creator:
        type: boolean
        example: true
      user_tags:
        $ref: '#/definitions/Tags'
      pair_tags:
        $ref: '#/definitions/Tags'
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  Event:
    type: object
    properties:
      name:
        type: string
        example: fun event
      description:
        type: string
        example: enormously fun event
      begin_date:
        type: string
        format: date-time
        example: 11.01.2002 12:00
      end_date:
        type: string
        format: date-time
        example: 11.01.2002 12:00
      tags:
        $ref: '#/definitions/Tags'
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  Space:
    type: object
    properties:
      space_id:
        type: integer
        example: 1234
      space_name:
        type: string
        example: test
      space_description:
        type: string
        example: space for test
      tags:
        $ref: '#/definitions/TagOptions'
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  TagOptions:
    type: array
    items:
      type: object
      additionalProperties:
        type: array
        items:
          type: string
        example:
          - '1'
          - '2'
          - '3'
      example:
        course:
          - math
          - cs
          - philosophy
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  Tags:
    type: array
    items:
      type: object
      additionalProperties:
        type: string
      example:
        course: math


    
    



